version: '3'
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=hogehoge-dev
      - CHOKIDIR_USEPOLLING=true
    # env_file:
    #   - ./.env
